extend-exclude = ["Test"]
line-length = 118

[lint.mccabe]
# Flag errors (C901) whenever the complexity level exceeds this value
max-complexity = 15

[lint.pylint]
max-nested-blocks = 7

[lint]
preview = true
select = ["ALL"]
ignore = [
    # Missing copyright information, should probably fix this at some point
    "CPY001",

    # Documentation stuff, eventually I should remove these and add more documentation
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D105",  # Missing docstring in magic method
    "D107",  # Missing dosctring in __init__

    # Guidelines for writing docstrings, I do not like these
    "D413", "DOC201", "DOC501",

    # Replace lambda with function from operator module, very unnecessary
    "FURB118",

    # Use specific rule codes when ignoring type issues (Pylance doesn't support this!)
    "PGH003",

    # Too many public methods/return statements, I get it but it's silly
    "PLR0904", "PLR0911",

    # Magic constants, good rule but frequently has false positives
    "PLR2004",

    # Method could be a function, class method, or static method (lots of false positives)
    "PLR6301",

    # Stupid rule about preferring double quotes over single quotes
    "Q000",

    # Security stuff that doesn't really apply for this project (famous last words)
    "S105", "S311", "S606",

    # Replace if-else with ternary operator, frequently a terrible suggestion for readability
    "SIM108",

    # Conditionally import if type-checking is enabled, unnecessary IMO
    "TC002", "TC003",

    # TODO stuff, good suggestions but not relevant for this project
    "TD001", "TD002", "TD003",

    # Whitespace (unnecessary as editor fixes this upon save)
    "W291", "W292", "W293"
]

[lint.per-file-ignores]
"command_list.py" = [
    "RUF029",  # Async function doesn't need to be async, all false positives in this file
    "D103"
]

"unit_test.py" = [
    "RUF029",
    "D102",
    "D103",
    "D105",
    "D107",
]

"sync.py" = [
    "S602", "S603"
]
