extend-exclude = ["Test"]
line-length = 135

[lint]
preview = true
select = ["ALL"]
ignore = [  # Remove these at your own peril
    "B903",
    "CPY001",
    "D101", "D102", "D103", "D105", "D107",
    "DTZ005",
    "FURB118",
    "PERF401",
    "PGH003",
    "PLR0904", "PLR0911", "PLR0913", "PLR2004", "PLR6301",
    "Q000",
    "RET504",
    "RUF029",
    "S102", "S105", "S311", "S602", "S603", "S606",  # Yes yes I know
    "SIM108",
    "W291", "W292", "W293" # These ones are trailing whitespace, I have them disabled because vscode removes trailing whitespace when I save files
]
